In [17]:
# 리스트의 shape을 보는 기능
import numpy as np

first_list = [1, 2, 3, 4, 5, 6]

# 1차원이면 shape에 뒤쪽 출력은 공백임
a = np.array(first_list)
print(a.shape) # tuple로 확인

# 만약 일정하게 리스트가 존재하지 않으면 그 차원은 없다고 생각
second_list = [[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]
second_list_odd = [[[1,2,3],[4,5]], [[7,8,9],[10,11,12]]]
b = np.array(second_list)
c = np.array(second_list_odd)
print(b.shape, c.shape) 

(6,)
(2, 2, 3) (2, 2)


In [39]:
# numpy로 배열 만들기
import numpy as np

# zeros와 ones는 제공한 만큼 0 또는 1로 채움
a = np.zeros((2, 2))
print(a)
b = np.full((2, 5), 10)
print(b)
c = np.eye(3)
print(c)
# range 안의 숫자만큼을 1씩 늘려 배열 생성
d = np.array(range(20)).reshape((2,10))
print(d)

[[0. 0.]
 [0. 0.]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [57]:
# numpy로 슬라이싱, 정수 인덱싱
import numpy as np

list1 = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(list1)
print(arr)

# 마지막 인덱스 전까지 ex)[0:2] -> 0~1
a = arr[1:2, 0:2]
print(a, end='\n\n')

list2 = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
b = np.array(list2)
# 0번째 행의 1번째, 2번째 행의 3번째
# 첫 번째 괄호는 row1, row2를 의미하고 뒤는 col1, col2를 의미
# 차원별로 선택되기 때문임
t = b[[0,2,1],[1,3,2]]
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]]

[ 2 12  7]
